# Exported from:        http://pop-os:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Tue Dec 21 23:02:02 CET 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: folder1
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.token
    value: !value "xlrelease_PasswordStringVariable_folder_token_value"
  - type: xlrelease.StringVariable
    key: folder.teststringexternal
- pattern: pattern1
  stages:
  - stage: New Stage
- template: template2
  scheduledStartDate: 2021-12-20T09:00:00+01:00
  dueDate: 2021-12-20T10:00:00+01:00
  phases:
  - phase: phase1 new edit
  riskProfile: Default risk profile
- name: dashboard
  type: xlrelease.BlankDashboard
  owner: admin
