# Exported from:        http://pop-os:5516/
# Release version:      22.1.0-121.113
# Date created:         Fri Jan 21 12:59:03 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder1
spec:
- name: jenkins1
  type: jenkins.Server
  url: test
  username: test
  password: !value "jenkins_Server_jenkins1_password"
  apiToken: !value "jenkins_Server_jenkins1_apiToken"
- pattern: pattern1
  stages:
  - stage: New Stage
- template: template2
  scheduledStartDate: 2021-12-20T09:00:00+01:00
  dueDate: 2021-12-20T10:00:00+01:00
  phases:
  - phase: phase1 new edit
  variables:
  - type: xlrelease.StringVariable
    key: testlb
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - a
      - b
      - c
    value: a
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_template2_scriptUserPassword"
  riskProfile: Default risk profile
- name: dashboard
  type: xlrelease.BlankDashboard
  owner: admin
