# Exported from:        http://pop-os:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Tue Feb 15 13:31:34 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: folder1
spec:
- name: jenkins1
  type: jenkins.Server
  url: test
  username: test
- pattern: pattern1
  stages:
  - stage: New Stage
- template: template2
  scheduledStartDate: 2021-12-20T09:00:00+01:00
  dueDate: 2021-12-20T10:00:00+01:00
  phases:
  - phase: phase1 new edit
  variables:
  - type: xlrelease.StringVariable
    key: testlb
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - a
      - b
      - c
    value: a
  scriptUsername: admin
  riskProfile: Default risk profile
- name: dashboard
  type: xlrelease.BlankDashboard
  owner: admin
