# Exported from:        http://pop-os:5516/
# Release version:      10.4.0-SNAPSHOT
# Date created:         Tue Jan 11 12:00:05 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: folder1
spec:
- template: template1
  scheduledStartDate: 2021-12-21T09:00:00+01:00
  dueDate: 2021-12-21T10:00:00+01:00
  phases:
  - phase: New Phase
  variables:
  - type: xlrelease.StringVariable
    key: var1
    value: value5
  - type: xlrelease.StringVariable
    key: listbox
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - a
      - b
      - c
    value: b
  riskProfile: Default risk profile
