# Exported from:        http://pop-os:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Mon Dec 20 18:33:43 CET 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: folder1
spec:
- folderVariables:
  - type: xlrelease.PasswordStringVariable
    key: folder.token
    value: !value "xlrelease_PasswordStringVariable_folder_token_value"
- template: template1
  scheduledStartDate: 2021-12-20T09:00:00+01:00
  phases:
  - phase: phase1
  riskProfile: Default risk profile
