# Exported from:        http://pop-os:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Wed Nov 24 18:37:37 CET 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: f1
spec:
- name: conf1
  type: jenkins.Server
  url: url
  username: username
  password: !value "jenkins_Server_conf1_password"
- name: conf2
  type: jenkins.Server
  url: url
  password: !value "jenkins_Server_conf2_password"
- pattern: pattern1
  stages:
  - stage: New Stage
- pattern: pattern2
  stages:
  - stage: New Stage
- template: template1
  scheduledStartDate: 2021-10-26T09:00:00+02:00
  dueDate: 2021-10-26T10:00:00+02:00
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- template: template2
  scheduledStartDate: 2021-10-26T09:00:00+02:00
  dueDate: 2021-10-26T10:00:00+02:00
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- name: dasboard1
  type: xlrelease.BlankDashboard
  owner: admin
- name: dashboard2
  type: xlrelease.BlankDashboard
  owner: admin
- name: trigger1
  type: time.Schedule
  releaseTitle: trigger1_release
  template: template1
  pollType: REPEAT
  periodicity: "10000"
  enabled: false
  triggerTime: 2021-11-05T14:24:46.607000
- name: trigger2
  type: time.Schedule
  releaseTitle: trigger2_release
  template: template2
  pollType: REPEAT
  periodicity: "10000"
  enabled: false
  triggerTime: 2021-11-05T14:25:11.971000
- directory: f1_sub
  children:
  - pattern: sub1p1
    stages:
    - stage: New Stage
  - template: template1_sub
    scheduledStartDate: 2021-11-05T09:00:00+01:00
    dueDate: 2021-11-05T10:00:00+01:00
    phases:
    - phase: New Phase
    riskProfile: Default risk profile
