# Exported from:        http://pop-os:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Tue Feb 22 16:06:59 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: f1
spec:
- name: f1_jenkins
  type: jenkins.Server
  url: a
- name: f2_jenkins
  type: jenkins.Server
  url: a
- template: template1
  scheduledStartDate: 2021-12-06T09:00:00+01:00
  dueDate: 2021-12-06T10:00:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: internal jenkins
      type: jenkins.Build
      jenkinsServer: f2_jenkins
      jobName: job
    - name: external jenkins
      type: jenkins.Build
      jenkinsServer: f1_jenkins
      jobName: job2
    - name: a
      type: xlrelease.Task
      description: '!value xlrelease_Release_template1_scriptUserPassword'
  scriptUsername: admin
  riskProfile: Default risk profile
- name: trigger1
  type: time.Schedule
  releaseTitle: test
  template: template1
  releaseFolder: ./
  pollType: REPEAT
  periodicity: "1000000"
  enabled: false
