# Exported from:        http://pop-os:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Wed Nov 03 11:07:20 CET 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: f1
spec:
- directory: sub1
  children:
  - pattern: sub1p1
    stages:
    - stage: New Stage
  - template: sub1t1_changedNameAgain
    scheduledStartDate: 2021-10-28T09:00:00+02:00
    dueDate: 2021-10-28T10:00:00+02:00
    phases:
    - phase: New Phase
    riskProfile: Default risk profile
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.var1
  - type: xlrelease.StringVariable
    key: folder.var2
- pattern: pattern1
  stages:
  - stage: New Stage
- pattern: pattern2
  stages:
  - stage: New Stage
- template: template1
  scheduledStartDate: 2021-10-26T09:00:00+02:00
  dueDate: 2021-10-26T10:00:00+02:00
  phases:
  - phase: New Phase
    tasks:
    - name: a
      type: xlrelease.Task
    - name: b
      type: xlrelease.Task
    - name: c
      type: xlrelease.Task
    - name: abc
      type: jenkins.Build
      jenkinsServer: jenkins1
  riskProfile: Default risk profile
- template: template2
  scheduledStartDate: 2021-10-26T09:00:00+02:00
  dueDate: 2021-10-26T10:00:00+02:00
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
---
apiVersion: xl-release/v1
kind: Permissions
metadata:
  home: f1
spec:
- directory: "."
  teams:
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - folder#view
    - template#edit_security
    - template#create_release
    - template#edit_triggers
    - template#edit_precondition
    - template#edit_failure_handler
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_security
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#lock_task
    - release#start
    - release#edit_blackout
    - release#edit_failure_handler
    - folder#view
    - release#abort
    - release#edit_task_script
    - release#edit_task_configuration_facet
    - release#edit_task_flag
    - release#edit_task_dates
    - release#edit_task
  - name: Folder Owner
    users:
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - delivery#edit
    - folder#view_versions
    - folder#apply_changes
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
    - folder#generate_configuration
- directory: sub1
  teams:
  - name: Template Owner
    users:
    - admin
    permissions:
    - template#edit
    - trigger#view_trigger
    - template#lock_task
    - template#view
    - folder#view
    - template#edit_security
    - template#create_release
    - template#edit_triggers
    - template#edit_precondition
    - template#edit_failure_handler
  - name: Release Admin
    users:
    - admin
    permissions:
    - release#edit_precondition
    - release#edit
    - release#edit_task_attachments
    - release#task_transition
    - trigger#view_trigger
    - release#reassign_task
    - release#edit_task_input_output_properties
    - release#edit_task_tags
    - release#edit_security
    - release#edit_task_description
    - trigger#edit_trigger
    - release#view
    - release#lock_task
    - release#start
    - release#edit_blackout
    - release#edit_failure_handler
    - folder#view
    - release#abort
    - release#edit_task_script
    - release#edit_task_configuration_facet
    - release#edit_task_flag
    - release#edit_task_dates
    - release#edit_task
  - name: Folder Owner
    users:
    - admin
    permissions:
    - folder#edit_variables
    - delivery_pattern#edit
    - folder#edit_configuration
    - delivery#edit
    - folder#view_versions
    - folder#apply_changes
    - group#view
    - folder#edit_versions
    - folder#edit_notifications
    - delivery_pattern#view
    - group#edit
    - delivery#view
    - delivery#edit_tracked_item
    - folder#view
    - folder#edit_security
    - dashboard#edit
    - folder#edit
    - dashboard#view
    - folder#generate_configuration
