# Exported from:        http://pop-os:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Wed Nov 03 11:59:22 CET 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: f1
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.jira_server_pass
    valueProvider:
      type: test.Test2ValueProvider
      jiraServer: test_jira_server
      username: admin
- pattern: pattern1
  stages:
  - stage: New Stage
- pattern: pattern2
  stages:
  - stage: New Stage
- template: template1
  scheduledStartDate: 2021-10-26T09:00:00+02:00
  dueDate: 2021-10-26T10:00:00+02:00
  phases:
  - phase: New Phase
    tasks:
    - name: a
      type: xlrelease.Task
    - name: b
      type: xlrelease.Task
    - name: c
      type: xlrelease.Task
    - name: abc
      type: jenkins.Build
      jenkinsServer: jenkins1
  riskProfile: Default risk profile
- template: template2
  scheduledStartDate: 2021-10-26T09:00:00+02:00
  dueDate: 2021-10-26T10:00:00+02:00
  phases:
  - phase: New Phase
  riskProfile: Default risk profile
- directory: sub1
  children:
  - pattern: sub1p1
    stages:
    - stage: New Stage
  - template: sub1t1_changedNameAgain
    scheduledStartDate: 2021-10-28T09:00:00+02:00
    dueDate: 2021-10-28T10:00:00+02:00
    phases:
    - phase: New Phase
    riskProfile: Default risk profile
