# Exported from:        http://pop-os:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Mon Dec 20 12:52:40 CET 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: f1
spec:
- template: template1
  scheduledStartDate: 2021-12-06T09:00:00+01:00
  dueDate: 2021-12-06T10:00:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: internal jenkins
      type: jenkins.Build
      jenkinsServer: f2_jenkins
      username: admin
      password: !value "jenkins_Build_internal_jenkins_password"
      jobName: job
    - name: external jenkins
      type: jenkins.Build
      jenkinsServer: f1_jenkins
      jobName: job2
    - name: a
      type: xlrelease.Task
      description: '!value xlrelease_Release_template1_scriptUserPassword'
    - name: a
      type: delivery.CreateDelivery
      pattern: f2/pattern
      folder: f2
  scriptUsername: admin
  scriptUserPassword: !value "xlrelease_Release_template1_scriptUserPassword"
  riskProfile: Default risk profile
- name: trigger1
  type: time.Schedule
  releaseTitle: test
  template: template1
  releaseFolder: f2
  pollType: REPEAT
  periodicity: "1000000"
  enabled: false
  triggerTime: 2021-11-05T14:24:46.607Z
- directory: f2
  children:
  - template: template1
    scheduledStartDate: 2021-12-20T09:00:00+01:00
    phases:
    - phase: New Phase
    riskProfile: Default risk profile
  - name: dashboard1
    type: xlrelease.BlankDashboard
    owner: admin
    tiles:
    - name: Active releases
      type: live.ReleasesTile
      row: 0
      col: 0
      filters:
      - type: xlrelease.FolderFilter
        folder: ./
      - type: xlrelease.DateFilter
        timeFrame: LAST_MONTH
  - name: trigger2
    type: git.Poll
    enabled: false
    periodicity: "10000"
    releaseTitle: test
    template: template1
    releaseFolder: f2
    gitRepository: test git
