# Exported from:        http://pop-os:5516/
# Release version:      22.0.0-20211220-123974
# Date created:         Mon Feb 07 13:38:14 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: Folder1
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.teststringexternal
  - type: xlrelease.PasswordStringVariable
    key: folder.token
- template: template2
  scheduledStartDate: 2021-12-20T09:00:00+01:00
  dueDate: 2021-12-20T10:00:00+01:00
  phases:
  - phase: phase1
    tasks:
    - name: jenkins task
      type: jenkins.Build
      jenkinsServer: jenkins1
      password: !value "jenkins_Build_jenkins_task_password"
      apiToken: !value "jenkins_Build_jenkins_task_apiToken"
    - name: a
      type: xlrelease.GateTask
    - name: a
      type: delivery.CreateDelivery
      ^title: aaa
      pattern: ./pattern1
      folder: ./
    color: '#3d6c9e'
  variables:
  - type: xlrelease.StringVariable
    key: testlb
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - a
      - b
      - c
    value: a
  scriptUsername: admin
  riskProfile: Default risk profile
- name: dashboard
  type: xlrelease.BlankDashboard
  owner: admin
- name: trigger
  type: time.Schedule
  releaseTitle: a
  variables:
  - type: xlrelease.StringVariable
    key: testlb
    valueProvider:
      type: xlrelease.ListOfStringValueProviderConfiguration
      values:
      - a
      - b
      - c
    value: a
  template: template2
  releaseFolder: Samples & Tutorials
  pollType: REPEAT
  periodicity: "10101001"
  enabled: false
