# Exported from:        http://pop-os:5516/
# Release version:      22.1.0-310.113
# Date created:         Thu Mar 10 17:24:04 CET 2022

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: mastercard_demo
spec:
- template: demo template
  scheduledStartDate: 2022-03-10T09:00:00+01:00
  phases:
  - phase: New Phase
    tasks:
    - name: a
      type: xlrelease.Task
    - name: b
      type: xlrelease.Task
    - name: c
      type: xlrelease.Task
  riskProfile: Default risk profile
