# Exported from:        http://pop-os:5516/
# Release version:      10.2.0-20210603-123974
# Date created:         Thu Nov 04 14:25:27 CET 2021

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  home: test_folder1
spec:
- pattern: pattern1
  stages:
  - stage: New Stage
- name: trig1
  type: time.Schedule
  releaseTitle: "${triggerTime}_release"
  template: template1
  pollType: REPEAT
  periodicity: "1000"
  triggerTime: 2021-11-04T14:16:28.664000
